# Microprofile server properties
server.port=9000
server.host=0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics.rest-request.enabled=false

# Application properties. This is the default greeting
app.greeting=Hello


# Datasource properties
javax.sql.DataSource.ds1.dataSourceClassName=oracle.jdbc.pool.OracleDataSource
javax.sql.DataSource.ds1.dataSource.url=jdbc:oracle:thin:@localhost:1521:orcl
javax.sql.DataSource.ds1.dataSource.user=system
javax.sql.DataSource.ds1.dataSource.password=Oracle@2024
