create or replace trigger employees_audit_trigger
after 
INSERT or UPDATE or DELETE
on employees
for each row
declare
    l_operation_type varchar2(10);
    l_emp_id number;
begin
    l_operation_type := case
    when INSERTING then 'inserted'
    when UPDATING then 'updated'
    when DELETING then 'deleted'
    end;
    
    l_emp_id :=case
    when INSERTING then :NEW.employee_id
    when UPDATING then :OLD.employee_id
    when DELETING then :OLD.employee_id
    end;
    
    insert into EMPLOYEES_AUDIT(operation_type,by_user,operation_date,record_id) values(l_operation_type,USER,SYSDATE,l_emp_id); 
    
end;

create table employees_audit(
    audit_id number generated by default as identity primary key,
    operation_type varchar2(10),
    by_user varchar2(30),
    operation_date date,
    record_id number
);

drop table employees_audit;

insert into employees(employee_id, first_name, last_name, email,manager_id) values(107,'abcd','xyz','abcd@gmail.com',100);
select * from employees;
select * from employees_audit;

update employees set first_name='amitabh', last_name='bachchan' where employee_id=107;
delete from employees where employee_id=107;